'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib(limit):
	i = 2
	sum = 2
	list = [1, 2]
	fib = 2
	while fib < limit:
		fib = list[-1] + list[-2]
		if fib % 2 == 0:
			sum += fib
		list.append(list[-1] + list[-2])
		i+= 1
	print sum
	#print list

fib(4000000)




